"""Versioned, hand-written language probes derived from Odin's documented surface.

The native compiler must confirm every declared validity classification. Gaps
are retained in the denominator. Generated expression tests live in audit.py.
"""
from __future__ import annotations

CASES: list[dict] = []
REFERENCE = "https://odin-lang.org/docs/overview/"


def valid(name: str, category: str, body: str, prelude: str = "", *, required: bool = False):
    source = 'package completeness\n' + prelude + '\n@(export)\nprobe :: proc "c" (x: u32, p: [^]u8) -> u32 {\n p[31] = u8(x)\n' + body + '\n}\n'
    CASES.append(dict(name=name, category=category, validity="valid", source=source,
                      reference=REFERENCE, required_mir=required))


def invalid(name: str, category: str, body: str, prelude: str = "", *, raw: bool = False):
    source = ('package completeness\n' + body + '\n') if raw else ('package completeness\n'+prelude+'\n@(export)\nprobe :: proc "c" (x: u32, p: [^]u8) -> u32 {\n'+body+'\n}\n')
    CASES.append(dict(name=name, category=category, validity="invalid", source=source,
                      reference=REFERENCE, required_mir=True))

# Scalar semantics: use typed mutable locals so runtime wrap is not confused
# with invalid compile-time overflow. Narrow intermediate values are observable.
valid("u32-wrap", "scalars", 'a:=x; a+=1; return a', required=True)
valid("u8-intermediate", "scalars", 'a:=u8(x); return u32((a+a)/2)', required=True)
valid("u32-literal-left", "scalars", 'a:=1+x; a+=1; return a/2', required=True)
valid("unsigned-shift", "scalars", 'n:=x%80; a:=u32(1); return (a<<n) | (x>>n)', required=True)
valid("bool-short-circuit", "expressions", 'b:=false && touch(p); b=true || touch(p); if b && touch(p) {return u32(p[0])}; return 0', 'touch :: proc "contextless" (p:[^]u8)->bool {p[0]=p[0]+1; return true}', required=True)
valid("bitwise", "expressions", 'a:=x; a ~= 12; a &~= 4; return (a & 255) | (x &~ 7)', required=True)
valid("numeric-spelling", "scalars", 'return u32(0b1010 + 0o12 + 1_000 + 012)', required=True)
valid("unicode-rune", "scalars", "return u32('λ')", required=True)
valid("u16", "scalars", 'a:=u16(x); return u32(a+a)', required=True)
valid("u64", "scalars", 'a:=u64(x); return u32((a*a)>>32)', required=True)
valid("u128", "scalars", 'a:=u128(x); return u32((a*a)>>32)')
valid("signed-i8", "scalars", 'a:=i8(x%100); return u32(a/2)')
valid("signed-i16", "scalars", 'a:=i16(x%1000); return u32(a/3)')
valid("signed-i32", "scalars", 'a:=-i32(x%1000); return u32(-a/7)')
valid("signed-i64", "scalars", 'a:=-i64(x); return u32((-a)/13)')
valid("signed-int", "scalars", 'a:=int(x%1000); return u32(a-1+1)')
valid("unsigned-uint", "scalars", 'a:=uint(x); return u32(a/3)')
valid("float32", "scalars", 'a:=f32(x%128); return u32(a*1.5)')
valid("float64", "scalars", 'a:=f64(x%128); return u32(a/0.5)')
valid("complex", "scalars", 'a:=complex(f32(x%128), f32(2)); return u32(real(a)+imag(a))')
valid("quaternion", "scalars", 'a:=quaternion(real=f32(x%128), imag=f32(1), jmag=f32(2), kmag=f32(3)); return u32(real(a))')
valid("endian-integer", "scalars", 'a:=u32be(x); return u32(a)')
valid("distinct-type", "types", 'a:=Counter(x); return u32(a+1)', 'Counter :: distinct u32')
valid("type-alias", "types", 'a:=Counter(x); return a+1', 'Counter :: u32')
valid("enum", "types", 'a:=Choice.A; if (x&1)!=0 {a=.B}; return u32(a)', 'Choice :: enum u32 {A=3, B=7}')
valid("bit-set", "types", 's:=Flags{.A,.C}; if .A in s {return 7}; return 0', 'Flag :: enum {A,B,C}\nFlags :: bit_set[Flag;u8]')
# Procedures, scopes and evaluation ordering.
valid("nested-calls", "procedures", 'return pair(inc(x), inc(2))', 'inc :: proc "contextless" (x:u32)->u32 {return x+1}\npair :: proc "contextless" (a,b:u32)->u32 {return a*100+b}', required=True)
valid("ordered-call-effects", "procedures", 'return pair(next(p),next(p))', 'next :: proc "contextless" (p:[^]u8)->u32 {p[0]=p[0]+1;return u32(p[0])}\npair :: proc "contextless" (a,b:u32)->u32 {return a*100+b}', required=True)
valid("recursion", "procedures", 'return fact(x%8)', 'fact :: proc "contextless" (n:u32)->u32 {if n<2 {return 1};return n*fact(n-1)}', required=True)
valid("default-argument", "procedures", 'return plus(x)', 'plus :: proc "contextless" (a:u32,b:u32=3)->u32 {return a+b}')
valid("named-argument", "procedures", 'return pair(b=x,a=7)', 'pair :: proc "contextless" (a,b:u32)->u32 {return a*100+b}')
valid("multiple-returns", "procedures", 'a,b:=pair(x); return a+b', 'pair :: proc "contextless" (x:u32)->(u32,u32) {return x,7}')
valid("named-return", "procedures", 'return f(x)', 'f :: proc "contextless" (x:u32)->(r:u32) {r=x+7;return}')
valid("procedure-value", "procedures", 'f:=inc; return f(x)', 'inc :: proc "contextless" (x:u32)->u32 {return x+1}')
valid("generic-procedure", "procedures", 'return id(x)', 'id :: proc "contextless" (a:$T)->T {return a}')
valid("overload-set", "procedures", 'return f(x)', 'fu :: proc "contextless" (x:u32)->u32 {return x+1}\nfi :: proc "contextless" (x:i32)->i32 {return x+2}\nf :: proc{fu,fi}')
valid("default-context", "runtime", 'context = runtime.default_context();return f(x)', 'import "base:runtime"\nf :: proc (x:u32)->u32 {return x+1}')
valid("lexical-shadow", "scope", 'a:=u32(7); total:=u32(0); {a:=u32(9);total+=a};return a*100+total', required=True)
valid("zero-initialization", "scope", 'n:u32; flag:bool; q:[^]u8; if !flag && q==nil {return n};return 9', required=True)
valid("local-constant", "scope", 'K :: u32(7); return x+K')
valid("parallel-assignment", "scope", 'a:=x;b:=u32(7);a,b=b,a;return a*100+b')
valid("multi-declaration", "scope", 'a,b:=x,u32(7);return a+b')
# Control-flow breadth with compositional cleanup and side effects.
valid("all-paths-return", "control", 'if (x&1)!=0 {return 11} else {return 22}', required=True)
valid("if-initializer", "control", 'if a:=x&7; a<3 {return a};return 8', required=True)
valid("range-half-open", "control", 'n:=u32(0);for i in 0..<u32(7) {n+=i};return n+x', required=True)
valid("range-inclusive-max", "control", 'n:=u32(0);a:=u8(254);b:=u8(255);for i in a..=b {n+=u32(i)};return n', required=True)
valid("range-dynamic-bound", "control", 'p[0]=5;n:=u32(0);for i in 0..<bound(p) {n+=i;p[0]=2};return n', 'bound :: proc "contextless" (p:[^]u8)->u32 {return u32(p[0])}', required=True)
valid("for-three-clause", "control", 'n:=u32(0);for i:=u32(0);i<6;i+=1 {n+=i};return n+x', required=True)
valid("for-condition", "control", 'n:=u32(0);for n<6 {n+=1};return n+x', required=True)
valid("for-infinite-break", "control", 'n:=u32(0);for {n+=1;if n==5 {break}};return n+x', required=True)
valid("for-continue", "control", 'n:=u32(0);for i:=u32(0);i<7;i+=1 {if i==3 {continue};n+=i};return n', required=True)
valid("range-break-continue", "control", 'n:=u32(0);for i in 0..<u32(8) {if i==2 {continue};if i==6 {break};n+=i};return n', required=True)
valid("labeled-break", "control", 'n:=u32(0);outer: for i in 0..<u32(4) {for j in 0..<u32(4) {n+=i+j;if n>2 {break outer}}};return n', required=True)
valid("labeled-continue", "control", 'n:=u32(0);outer: for i in 0..<u32(4) {for j in 0..<u32(4) {n+=i+j;continue outer}};return n', required=True)
valid("ternary-lazy", "expressions", 'return (x&1)!=0 ? next(p) : u32(9)', 'next :: proc "contextless" (p:[^]u8)->u32 {p[0]=p[0]+1;return u32(p[0])}', required=True)
valid("switch-values", "control", 'switch x&3 {case 0:return 7;case 1,2:return 8;case:return 9}')
valid("switch-range", "control", 'switch x%20 {case 0..<10:return 1;case 10..=15:return 2;case:return 3}')
valid("switch-fallthrough", "control", 'a:=u32(0);switch x&1 {case 0:a+=1;fallthrough;case:a+=2};return a')
valid("when", "metaprogramming", 'when size_of(u32)==4 {return x+1} else {return 0}')
valid("defer-lifo", "cleanup", 'defer p[0]=p[0]*10+1;defer p[0]=p[0]*10+2;return x', required=True)
valid("defer-return-snapshot", "cleanup", 'a:=x;defer a=7;return a', required=True)
valid("defer-observes-exit-value", "cleanup", 'a:=u32(1);defer p[0]=u8(a);a=9;return x', required=True)
valid("defer-shadow-binding", "cleanup", 'a:=u32(7);defer p[0]=u8(a);{a:=u32(9);defer p[1]=u8(a);return x}', required=True)
valid("defer-branch-exits", "cleanup", 'defer p[0]=p[0]+1;if (x&1)==0 {return 7};return 9', required=True)
valid("defer-continue-break", "cleanup", 'n:=u32(0);for i in 0..<u32(6) {defer p[0]=p[0]+1;if i==1 {continue};if i==3 {break};n+=i};return n', required=True)
valid("defer-labeled-exit", "cleanup", 'outer: for i in 0..<u32(3) {defer p[0]=p[0]+1;for j in 0..<u32(3) {defer p[1]=p[1]+1;if i+j==2 {break outer}}};return x', required=True)
# Indexed places must resolve before RHS side effects, without double evaluation.
valid("indexed-compound", "memory", 'p[0]+=u8(x);p[0]~=u8(13);return u32(p[0])', required=True)
valid("indexed-effects", "memory", 'p[idx(p)]=value(p);return u32(p[0])*100+u32(p[1])', 'idx :: proc "contextless" (p:[^]u8)->u32 {p[0]=1;return 1}\nvalue :: proc "contextless" (p:[^]u8)->u8 {p[0]=2;return 9}', required=True)
valid("indexed-compound-effects", "memory", 'p[0]=3;p[idx(p)]+=value(p);return u32(p[0])*100+u32(p[1])', 'idx :: proc "contextless" (p:[^]u8)->u32 {p[1]=p[1]+1;return 0}\nvalue :: proc "contextless" (p:[^]u8)->u8 {p[0]=7;return 2}', required=True)
valid("pointer-deref", "memory", 'a:=u32(3);q:=&a;q^=x;return a')
valid("fixed-array", "aggregates", 'a:=[4]u32{1,2,3,4};a[x%4]+=1;return a[0]+a[1]+a[2]+a[3]')
valid("struct", "aggregates", 's:=Pair{x,7};s.b+=1;return s.a+s.b', 'Pair :: struct {a,b:u32}')
valid("struct-by-value", "aggregates", 's:=make_pair(x);return s.a+s.b', 'Pair :: struct {a,b:u32}\nmake_pair :: proc "contextless" (x:u32)->Pair {return Pair{x,7}}')
valid("using-struct", "aggregates", 's:=Outer{Inner{7},x};return s.a+s.b', 'Inner :: struct {a:u32}\nOuter :: struct {using inner:Inner,b:u32}')
valid("array-vector-arithmetic", "aggregates", 'a:=[2]u32{x,1};b:=[2]u32{2,3};c:=a+b;return c[0]+c[1]')
valid("matrix-type", "aggregates", 'm:=matrix[2,2]f32{1,2,3,4};return u32(m[0,0]+m[1,1])')
valid("slice", "containers", 'a:=[4]u32{1,2,3,4};s:=a[:];return s[x%4]+u32(len(s))')
valid("dynamic-array", "containers", 'context = runtime.default_context();a:=make([dynamic]u32);defer delete(a);append(&a,x,7);return a[0]+a[1]', 'import "base:runtime"')
valid("map", "containers", 'context = runtime.default_context();m:=make(map[u32]u32);defer delete(m);m[7]=x;v,ok:=m[7];if ok {return v};return 0', 'import "base:runtime"')
valid("string", "containers", 's:="hello";return u32(s[x%5])+u32(len(s))')
valid("string-iteration", "containers", 'n:=u32(0);for r in "λa" {n+=u32(r)};return n')
valid("union-assert", "types", 'v:Value=x;a,ok:=v.(u32);if ok {return a};return 0', 'Value :: union {u32,bool}')
valid("type-switch", "types", 'v:Value=x;switch a in v {case u32:return a;case bool:return u32(a);case:return 0}', 'Value :: union {u32,bool}')
valid("typeid", "metaprogramming", 'if type_of(x)==u32 {return 1};return 0')
valid("size-align", "metaprogramming", 'return u32(size_of(u32)+align_of(u32))')
valid("compile-assert", "metaprogramming", '#assert(size_of(u32)==4);return x')
valid("core-import", "packages", 'return bits.count_ones(x)', 'import "core:math/bits"')
valid("local-import", "packages", 'return helper.inc(x)', 'import helper "helper"')
CASES[-1]["files"] = {"helper/main.odin": 'package helper\ninc :: proc "contextless" (x:u32)->u32 {return x+1}\n'}
valid("mutable-global", "runtime", 'g=x;g+=1;return g', 'g:u32')
valid("foreign-proc", "runtime", 'return u32(abs(-i32(x%100)))', 'foreign import libc "system:c"\nforeign libc {abs :: proc "c" (x:i32)->i32 ---}')
valid("custom-link-name", "runtime", 'return renamed(x)', '@(link_name="other_symbol")\nrenamed :: proc "c" (x:u32)->u32 {return x+1}')

# Compiler rejection parity must occur before C emission. A later C error does
# not count as a correct Odin diagnostic.
invalid("reject-parameter-write", "diagnostics", 'x=7;return x')
invalid("reject-argument-count", "diagnostics", 'return f()', 'f :: proc "c" (x:u32)->u32 {return x}')
invalid("reject-argument-type", "diagnostics", 'return f(true)', 'f :: proc "c" (x:u32)->u32 {return x}')
invalid("reject-return-type", "diagnostics", 'return true')
invalid("reject-missing-return", "diagnostics", 'if x==0 {return 1}')
invalid("reject-empty-return", "diagnostics", 'return')
invalid("reject-void-return", "diagnostics", 'f :: proc "c" () {return 1}', raw=True)
invalid("reject-void-arithmetic", "diagnostics", 'return f()+x', 'f :: proc "c" () {}')
invalid("reject-void-argument", "diagnostics", 'return g(f())', 'f :: proc "c" () {}\ng :: proc "c" (x:u32)->u32 {return x}')
invalid("reject-scope-escape", "diagnostics", '{a:=u32(3)};return a')
invalid("reject-loop-scope", "diagnostics", 'for i in 0..<u32(4) {};return i')
invalid("reject-duplicate-local", "diagnostics", 'a:=u32(1);a:=u32(2);return a')
invalid("reject-duplicate-proc", "diagnostics", 'f :: proc "c" () {}\nf :: proc "c" () {}', raw=True)
invalid("reject-bool-arithmetic", "diagnostics", 'a:=true;return u32(a+a)')
invalid("reject-mixed-integers", "diagnostics", 'a:=u8(x);return x+a')
invalid("reject-condition-type", "diagnostics", 'if x {return 1};return 0')
invalid("reject-constant-cast", "constants", 'return u32(u8(256))')
invalid("reject-constant-add", "constants", 'return u32(u8(200)+u8(100))')
invalid("reject-constant-shift", "constants", 'return u32(u8(1)<<8)')
invalid("reject-constant-divzero", "constants", 'return u32(1)/u32(0)')
invalid("reject-global-overflow", "constants", 'return u32(K+1)', 'K :: u8(255)')
invalid("reject-wide-literal", "constants", 'return u32(18446744073709551616)')
invalid("reject-constant-write", "diagnostics", 'K=9;return K', 'K :: u32(7)')
invalid("reject-break-outside", "diagnostics", 'break;return x')
invalid("reject-continue-outside", "diagnostics", 'continue;return x')
invalid("reject-missing-label", "diagnostics", 'for {break nowhere};return x')
invalid("reject-ternary-types", "diagnostics", 'return x==0 ? true : x')
invalid("reject-bad-syntax", "diagnostics", 'return (x + )')
invalid("reject-unknown-name", "diagnostics", 'return not_declared')
invalid("reject-unreachable-type-error", "diagnostics", 'return x;bad:u32=true')
invalid("reject-unreachable-break", "diagnostics", 'return x;break')
invalid("reject-explicit-unknown-type", "diagnostics", 'a:Missing=1;return a')
invalid("reject-index-type", "diagnostics", 'return u32(p[true])')
invalid("reject-pointer-add", "diagnostics", 'q:=p+p;return u32(q[0])')
invalid("reject-default-argument-type", "diagnostics", 'return x', 'f :: proc "c" (a:u32=true)->u32 {return a}')
invalid("reject-zero-static-assert", "metaprogramming", '#assert(false);return x')

# Keep inferred signed semantics visible even before signed lowering is present.
valid("default-integer-inference", "scalars", 'a:=1;a-=2;return u32(a/2)')
valid("u16-intermediate-multiply", "scalars", 'a:=u16(x);return u32((a*a)/3)', required=True)
valid("u64-oversized-shift", "scalars", 'a:=u64(x);n:=x%80;return u32((a<<n)>>32)', required=True)
valid("u64-inclusive-max", "control", 'n:=u32(0);a:=u64(18446744073709551614);b:=u64(18446744073709551615);for i in a..=b {n+=u32(i-a)+1};return n', required=True)
invalid("reject-u16-constant-overflow", "constants", 'return u32(u16(65536))')
invalid("reject-u64-constant-overflow", "constants", 'return u32(u64(18446744073709551615)+u64(1))')
