package main

import "core:fmt"
import "core:strings"

C_RUNTIME :: `/* Generated by Borr. Portable C99; explicit 64-bit scalar profile. */
#include <stdint.h>
#include <stdbool.h>
#include <limits.h>
#ifndef BOR_TRAP
# ifdef BOR_FREESTANDING
extern void bor_trap(void);
#  define BOR_TRAP() bor_trap()
# else
#  include <stdlib.h>
#  define BOR_TRAP() abort()
# endif
#endif

typedef char bor_requires_octets[(CHAR_BIT == 8) ? 1 : -1];

`

BOR_SIGNED :: `/* This conversion is defined by C99 even when the high bit is set. */
static inline int64_t bor_signed(uint64_t x) {
    return x <= INT64_MAX ? (int64_t)x : -1 - (int64_t)(UINT64_MAX - x);
}
`
BOR_SDIV :: `static inline int64_t bor_sdiv(int64_t a, int64_t b, int64_t minimum) {
    if (b == 0) { BOR_TRAP(); return 0; }
    if (a == minimum && b == -1) return minimum;
    return a / b;
}
`
BOR_SREM :: `static inline int64_t bor_srem(int64_t a, int64_t b) {
    if (b == 0) { BOR_TRAP(); return 0; }
    if (a == INT64_MIN && b == -1) return 0;
    return a % b;
}
`
BOR_UDIV :: `static inline uint64_t bor_udiv(uint64_t a, uint64_t b) {
    if (b == 0) { BOR_TRAP(); return 0; }
    return a / b;
}
`
BOR_UREM :: `static inline uint64_t bor_urem(uint64_t a, uint64_t b) {
    if (b == 0) { BOR_TRAP(); return 0; }
    return a % b;
}
`

c_type :: proc(type: Type) -> string {
    switch type {
    case .Void: return "void"
    case .Int, .I64: return "int64_t"
    case .I8: return "int8_t"
    case .I16: return "int16_t"
    case .I32: return "int32_t"
    case .U8: return "uint8_t"
    case .U16: return "uint16_t"
    case .U32: return "uint32_t"
    case .Uint, .U64, .Uintptr: return "uint64_t"
    case .Bool: return "bool"
    }
    unreachable()
}
c_signed_helper :: proc(t: Type) -> string {
    if bit_width(t) == 64 { return "bor_signed" }
    return fmt.tprintf("bor_signed%d", bit_width(t))
}
c_name :: proc(p: ^Procedure, id: int) -> string {
    if p.exported { return p.name }
    return fmt.tprintf("bor_p%d", id)
}
c_signature :: proc(b: ^strings.Builder, p: ^Procedure, id: int) {
    if !p.exported { strings.write_string(b, "static inline ") }
    fmt.sbprintf(b, "%s %s(", c_type(p.result), c_name(p, id))
    if p.parameter_count == 0 { strings.write_string(b, "void") }
    for i in 0..<p.parameter_count {
        if i > 0 { strings.write_string(b, ", ") }
        fmt.sbprintf(b, "%s bor_s%d", c_type(p.slots[i].type), i)
    }
    strings.write_string(b, ")")
}

reachable_code :: proc(p: ^Procedure) -> []bool {
    reachable := make([]bool, len(p.code))
    labels := make([]int, int(p.label_count)+1)
    for inst, i in p.code { if inst.op == .Label { labels[inst.target] = i } }
    work := make([dynamic]int)
    if len(p.code) > 1 { append(&work, 1) }
    for len(work) > 0 {
        i := pop(&work)
        if i >= len(p.code) || reachable[i] { continue }
        reachable[i] = true
        inst := p.code[i]
        if inst.op == .Return { continue }
        if inst.op == .Jump || inst.op == .Branch {
            append(&work, labels[inst.target])
            if inst.op == .Branch { append(&work, labels[inst.otherwise]) }
        } else { append(&work, i+1) }
    }
    return reachable
}

// Values are topologically numbered. One reverse walk removes dead pure
// expressions without erasing calls, traps, stores, or control flow.
live_code :: proc(p: ^Procedure, reachable: []bool) -> (keep, used: []bool) {
    keep = make([]bool, len(p.code))
    used = make([]bool, len(p.code))
    read_slots := make([]bool, len(p.slots))
    for inst,i in p.code { if reachable[i] && inst.op==.Load { read_slots[inst.slot]=true } }
    for i := len(p.code)-1; i > 0; i -= 1 {
        if !reachable[i] { continue }
        inst := p.code[i]
        effect := (inst.op == .Store && read_slots[inst.slot]) || inst.op == .Call || inst.op == .Label ||
                  inst.op == .Jump || inst.op == .Branch || inst.op == .Return ||
                  inst.op == .Assert || inst.op == .Div || inst.op == .Rem
        if !used[i] && !effect { continue }
        keep[i] = true
        if uses_a(inst) { used[inst.a] = true }
        if is_binary(inst.op) { used[inst.b] = true }
        if inst.op == .Call {
            for j in 0..<int(inst.args.count) { used[p.arguments[int(inst.args.start)+j]] = true }
        }
    }
    return
}
c_binary :: proc(b: ^strings.Builder, p: ^Procedure, inst: Instruction) {
    op: string
    #partial switch inst.op {
    case .Add: op = "+"
    case .Sub: op = "-"
    case .Mul: op = "*"
    case .And: op = "&"
    case .Or: op = "|"
    case .Xor: op = "^"
    case .And_Not: op = "& ~"
    case .Eq: op = "=="
    case .Ne: op = "!="
    case .Lt: op = "<"
    case .Le: op = "<="
    case .Gt: op = ">"
    case .Ge: op = ">="
    case .Div, .Rem:
        signed := is_signed(value_type(p, inst.a))
        helper := "bor_sdiv" if signed else "bor_udiv"
        if inst.op == .Rem { helper = "bor_srem" if signed else "bor_urem" }
        fmt.sbprintf(b, "%s(bor_v%d, bor_v%d", helper, inst.a, inst.b)
        if signed && inst.op == .Div { fmt.sbprintf(b, ", INT%d_MIN",bit_width(inst.type)) }
        strings.write_string(b,")")
        return
    }
    if is_signed(inst.type) && !is_compare(inst.op) {
        fmt.sbprintf(b, "%s((uint64_t)bor_v%d %s (uint64_t)bor_v%d)", c_signed_helper(inst.type), inst.a, op, inst.b)
    } else if !is_compare(inst.op) {
        fmt.sbprintf(b,"(%s)((uint64_t)bor_v%d %s (uint64_t)bor_v%d)",c_type(inst.type),inst.a,op,inst.b)
    } else { fmt.sbprintf(b, "(bor_v%d %s bor_v%d)", inst.a, op, inst.b) }
}

emit_c99 :: proc(program: ^Program) -> string {
    b: strings.Builder
    strings.write_string(&b, C_RUNTIME)
    retained := make([]bool, len(program.procs))
    work: [dynamic]Proc_Id
    for p, i in program.procs {
        if p.exported || p.name == "main" { append(&work, Proc_Id(i)) }
    }
    // Whole-program liveness starts from the public ABI, not from source order.
    signed_types: [Type]bool
    sdiv, srem, udiv, urem: bool
    for len(work) > 0 {
        id := pop(&work)
        if retained[id] { continue }
        retained[id] = true
        p := &program.procs[id]
        reachable := reachable_code(p)
        keep, used := live_code(p, reachable)
        for inst, i in p.code {
            if !keep[i] { continue }
            if inst.op == .Call { append(&work, inst.callee) }
            if is_signed(inst.type) && used[i] && (inst.op == .Const || inst.op == .Cast || inst.op == .Neg || inst.op == .Bit_Not || (is_binary(inst.op) && inst.op != .Div && inst.op != .Rem)) { signed_types[inst.type] = true }
            if inst.op == .Div {
                if is_signed(inst.type) { sdiv = true } else { udiv = true }
            }
            if inst.op == .Rem {
                if is_signed(inst.type) { srem = true } else { urem = true }
            }
        }
    }
    if signed_types[.Int] || signed_types[.I64] { strings.write_string(&b, BOR_SIGNED) }
    signed_widths := []Type{.I8,.I16,.I32}
    for type in signed_widths {
        if !signed_types[type] { continue }
        n := bit_width(type)
        fmt.sbprintf(&b,"static inline int%d_t bor_signed%d(uint64_t x) {{\n",n,n)
        fmt.sbprintf(&b,"    uint%d_t y = (uint%d_t)x;\n",n,n)
        fmt.sbprintf(&b,"    return y <= INT%d_MAX ? (int%d_t)y : (int%d_t)(-1 - (int64_t)(UINT%d_MAX - y));\n}\n",n,n,n,n)
    }
    if sdiv { strings.write_string(&b, BOR_SDIV) }
    if srem { strings.write_string(&b, BOR_SREM) }
    if udiv { strings.write_string(&b, BOR_UDIV) }
    if urem { strings.write_string(&b, BOR_UREM) }
    for &p, i in program.procs {
        if retained[i] { c_signature(&b, &p, i); strings.write_string(&b, ";\n") }
    }
    for &p, pi in program.procs {
        if !retained[pi] { continue }
        strings.write_string(&b, "\n")
        c_signature(&b, &p, pi)
        strings.write_string(&b, " {\n")
        reachable := reachable_code(&p)
        keep, used := live_code(&p, reachable)
        targets := make([]bool, int(p.label_count)+1)
        for inst, i in p.code {
            if !keep[i] { continue }
            if inst.op == .Branch || inst.op == .Jump { targets[inst.target] = true }
            if inst.op == .Branch { targets[inst.otherwise] = true }
        }
        used_slots := make([]bool,len(p.slots))
        for inst,i in p.code { if keep[i] && (inst.op==.Load || inst.op==.Store) { used_slots[inst.slot]=true } }
        for slot, i in p.slots {
            if i>=p.parameter_count && !used_slots[i] { continue }
            if i >= p.parameter_count { fmt.sbprintf(&b, "    %s bor_s%d = 0;\n", c_type(slot.type), i) }
            fmt.sbprintf(&b, "    (void)&bor_s%d;\n", i)
        }
        for inst, i in p.code {
            if keep[i] && used[i] && has_value(inst) { fmt.sbprintf(&b, "    %s bor_v%d;\n", c_type(inst.type), i) }
        }
        for inst, i in p.code {
            if !keep[i] { continue }
            if inst.op == .Label {
                if targets[inst.target] { fmt.sbprintf(&b, "bor_b%d:;\n", inst.target) }
                continue
            }
            fmt.sbprintf(&b, "    /* %d:%d */ ", inst.pos.line, inst.pos.column)
            if has_value(inst) {
                if used[i] { fmt.sbprintf(&b, "bor_v%d = ", i) }
                else { strings.write_string(&b, "(void)") }
            }
            #partial switch inst.op {
            case .Const:
                if inst.type == .Bool { strings.write_string(&b, "true" if inst.bits != 0 else "false") }
                else if is_signed(inst.type) { fmt.sbprintf(&b, "%s(UINT64_C(%d))", c_signed_helper(inst.type), inst.bits) }
                else { fmt.sbprintf(&b, "UINT64_C(%d)", inst.bits) }
            case .Load: fmt.sbprintf(&b, "bor_s%d", inst.slot)
            case .Store: fmt.sbprintf(&b, "bor_s%d = bor_v%d", inst.slot, inst.a)
            case .Cast:
                if is_signed(inst.type) { fmt.sbprintf(&b, "%s((uint64_t)bor_v%d)", c_signed_helper(inst.type), inst.a) }
                else { fmt.sbprintf(&b, "(%s)bor_v%d", c_type(inst.type), inst.a) }
            case .Neg:
                if is_signed(inst.type) { fmt.sbprintf(&b, "%s(UINT64_C(0) - (uint64_t)bor_v%d)", c_signed_helper(inst.type), inst.a) }
                else { fmt.sbprintf(&b, "(%s)(UINT64_C(0) - (uint64_t)bor_v%d)", c_type(inst.type), inst.a) }
            case .Not: fmt.sbprintf(&b, "(!bor_v%d)", inst.a)
            case .Bit_Not:
                if is_signed(inst.type) { fmt.sbprintf(&b, "%s(~(uint64_t)bor_v%d)", c_signed_helper(inst.type), inst.a) }
                else { fmt.sbprintf(&b, "(%s)(~(uint64_t)bor_v%d)", c_type(inst.type), inst.a) }
            case .Jump: fmt.sbprintf(&b, "goto bor_b%d", inst.target)
            case .Branch: fmt.sbprintf(&b, "if (bor_v%d) {{ goto bor_b%d; } else {{ goto bor_b%d; }", inst.a, inst.target, inst.otherwise)
            case .Return:
                if p.result == .Void { strings.write_string(&b, "return") }
                else { fmt.sbprintf(&b, "return bor_v%d", inst.a) }
            case .Assert: fmt.sbprintf(&b, "if (!bor_v%d) {{ BOR_TRAP(); }", inst.a)
            case .Call:
                callee := &program.procs[inst.callee]
                fmt.sbprintf(&b, "%s(", c_name(callee, int(inst.callee)))
                for j in 0..<int(inst.args.count) {
                    if j > 0 { strings.write_string(&b, ", ") }
                    fmt.sbprintf(&b, "bor_v%d", p.arguments[int(inst.args.start)+j])
                }
                strings.write_string(&b, ")")
            case: c_binary(&b, &p, inst)
            }
            strings.write_string(&b, ";\n")
        }
        strings.write_string(&b, "}\n")
    }
    if id, ok := program.names["main"]; ok { fmt.sbprintf(&b, "\nint main(void) {{ %s(); return 0; }\n", c_name(&program.procs[id], int(id))) }
    return strings.to_string(b)
}
